- name: Smoke test Python
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages | Base init
  apt: name={{ item }} state=present
  with_items:
      - apt-transport-https
      - vim
      - unzip
      - zip
      - curl
      - whois
      - telnet 
      - smartmontools
      - htop
      - bash-completion 
      - git
      - strace
      - screen
      - ntpdate 
      - python-software-properties
      - software-properties-common
      - build-essential
      - nginx

- name: Check whether port 80 is available
  wait_for:
    port: 80
    state: started
    timeout: 10
